_target_: src.datamodules.tu_graph_datamodule.TUGraphDataModule
dataset: "NCI1"
data_dir: ${paths.data_dir}
batch_size: 32
train_val_test_split: [0.8, 0.1, 0.1]
num_workers: 0
pin_memory: False
transform: "fast_scatter"
transform_args:
  alpha: 0
  power: 2
